
FAIL Test checks that notification constructor arguments can't be empty Test bug: unrecognized DOMException code "new TypeError()" passed to assert_throws()(stack: assert_throws@http://localhost:8800/resources/testharness.js:660:126
http://localhost:8800/notifications/notification-constructor-invalid.html:13:20
step@http://localhost:8800/resources/testharness.js:798:30
test@http://localhost:8800/resources/testharness.js:73:22
global code@http://localhost:8800/notifications/notification-constructor-invalid.html:12:9)

